# Basic
title: pei
subtitle: 
description: We Are Know So Little.
welcome_message: 
creator: <a href="https://peiyucn.github.io/">@pei</a>
url: "https://peiyu.github.io/"
permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: 豆瓣, description: 我的豆瓣, url: 'https://www.douban.com/people/pei830/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: vno-jekyll
    # duoshuo: peiyucn
# Social
social:
    # weibo: peiyucn
    # github: peiyucn
    mail: peiyu@live.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
